---
- name: Install & configure Nginx as a reverse proxy.
  hosts: webservers
  become: yes
  tasks:
    - name: Install required packages

- name: Install & configure Django + Gunicorn.
  hosts: webservers
  become: yes
  tasks:
    - name: Install required packages

- name: Setup PostgreSQL
  hosts: postgre
  become: yes
  tasks:
    - name: Install required packages

